scrape_configs:
  - job_name: 'surf-sense-api-metrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['surf-sense-api:8080']
        labels:
          application: 'Surf Sense Api'

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']